# name: 'Terraform Apply'

# on:
#   push:
#     branches:
#       - 'main'

# env:
#   TF_CLOUD_ORGANIZATION: "SoakDigital"
#   TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
#   TF_WORKSPACE: "tfc-getting-started"
#   CONFIG_DIRECTORY: "./terraform"